### ISSUE TITLE
Build failure: AppDelegate.h:13:9: fatal error: 'Sparkle/Sparkle.h' file not found

### ISSUE THREAD

**Issue by i0ntempest** [benbaker76/Hackintool#196]
Seems to be caused by https://github.com/benbaker76/Hackintool/commit/c957ef215db965bf967015d85afcc5e0b6f847ac where Sparkle (or the whole Frameworks dir) was removed.

**Comment by benbaker76** [comment]
Okay I just did a commit please let me know if it solves the issue,

**Comment by i0ntempest** [comment]
Thanks, it's now fixed
